/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alpha.c"
#include "bar_alternativetags.c"
#include "bar_ewmhtags.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_fancybar.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "alttab.c"
#include "attachx.c"
#include "cool_autostart.c"
#include "focusmaster.c"
#include "focusurgent.c"
#include "mpdcontrol.c"
#include "restartsig.c"
#include "rotatestack.c"
#include "scratchpad.c"
#include "setborderpx.c"
#include "swallow.c"
#include "vanitygaps.c"
#include "xrdb.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_fibonacci.c"
#include "layout_flextile-deluxe.c"
#include "layout_monocle.c"
#include "layout_tile.c"

